use older release of imglib2-algorithm to avoid issues with shaded jar
When using 0.11.1, gauss3() throws the exception when run as a shaded jar: "java.lang.NoClassDefFoundError: org/janelia/saalfeldlab/net/imglib2/algorithm/convolution/kernel/Kernel1D". Have not been able to find the cause so far.